# Setup
title:               The Reviews 
tagline:             
description:         'Expert reviews of the best NVRs: 4K, PoE, AI features, cross-brand compatibility, and enterprise-grade reliability for home & business surveillance.'  
url:                 https://thereviews.github.io 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:             
  url:               
  email:             
  
  
  social-network-links:
  email: "someone@example.com"
  
  

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
